name: littletest2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  provider: ^6.0.0
  flutter_local_notifications: ^17.2.3
  fl_chart: ^0.68.0

  # DB관련
  sqflite: ^2.2.6
  path: ^1.8.0
  path_provider: ^2.0.15
  table_calendar: ^3.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.32.12

  # aws cognito, 로그인 관련
  amazon_cognito_identity_dart_2: ^3.0.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
